### ISSUE TITLE
Rewrite README to use botometer

### ISSUE THREAD

**Issue by ryantmoore** [kurtawirth/botscan#10]
After we solve #9, the surviving `README` file needs to be updated to reflect using botometer.

**Comment by kurtawirth** [comment]
This has been completed as of commit [#9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3](https://github.com/kurtawirth/botscan/commit/9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3).

**Comment by kurtawirth** [comment]
This has been completed as of commit [#9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3](https://github.com/kurtawirth/botscan/commit/9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3)
