### ISSUE TITLE
Edit setup function documentation example

### ISSUE THREAD

**Issue by ryantmoore** [kurtawirth/botscan#16]
The current example is specified as

```
\dontrun{setup_botscan("a", "b", "c", "d", "e")}
```

If Issues #8 and #11 are resolved, and the user must still assign the output of `setup_botscan()` to a name in order to access `bom$check_account()`, then this should change to 

```
\dontrun{bom <- setup_botscan("a", "b", "c", "d", "e")}
```

**Comment by kurtawirth** [comment]
This has been completed as of commit [#9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3](https://github.com/kurtawirth/botscan/commit/9560af0ac68fbbccb10d24cfb5bf71d2454fdaa3)
