### ISSUE TITLE
Skip Broken Loops

### ISSUE THREAD

**Issue by kurtawirth** [kurtawirth/botscan#17]
Write code that skips a loop run if it encounters an error.

**Comment by kurtawirth** [comment]
Possible solutions:

https://stackoverflow.com/questions/14748557/skipping-error-in-for-loop
https://jonlefcheck.net/2013/05/20/continuing-a-for-loop-in-r-after-an-error/ & https://campus.datacamp.com/courses/intermediate-r-for-finance/loops-3?ex=12#skiponboarding

**Comment by ryantmoore** [comment]
Initial solution completed in commit 7047e72.

**Comment by kurtawirth** [comment]
This is working as expected; issue is now closed.
