### ISSUE TITLE
Fill in documentation for new arguments to botscan

### ISSUE THREAD

**Issue by ryantmoore** [kurtawirth/botscan#24]
Some documentation housekeeping before we think about reordering the arguments to group similar arguments together.  In the roxygen for `botscan.R`:

- [x] add detail to argument `timeout`
- [x] add detail to argument `parse`
- [x] reconcile the documentation for `threshold` (.899) with the encoded default (.43)
- [x] for logical clarity, change the argument name and default from `search = FALSE` to `stream = TRUE` (and adjust code as needed).

Then, let's think about the best argument order.

**Comment by kurtawirth** [comment]
Order: Search, Timeout, Threshold, User_Level, API Choice (change search to stream and make default TRUE), N_Tweets, Retweets, Parse, Verbose

**Comment by kurtawirth** [comment]
All completed as of update #c3fafcf91e666f1359786d21afae3138b93a54f7.
