### ISSUE TITLE
Add ability to query more versions of the Twitter API

### ISSUE THREAD

**Issue by ryantmoore** [kurtawirth/botscan#25]
Currently, `botscan()` allows users to specify whether to query the streaming API (the default) or the search API.

Are there other versions of the API we want to permit users to query?
* What are these versions?
* Can querying them be implemented via extant functions in `library(rtweet)`?
* Should we change our `stream`/`search` argument to a single argument called `api = "stream"` rather than the current logical?

**Comment by ryantmoore** [comment]
We agree that it makes sense to implement the third bullet above, a single argument `api`, defaulting to `"stream"`.  I'll add this to `botscan()`, document it, and recompile the package.

**Comment by kurtawirth** [comment]
[Site with Trends and User APIs, with helpful code](http://socialmedia-class.org/twittertutorial.html)

[Twitter API reference index](https://developer.twitter.com/en/docs/api-reference-index.html)

**Comment by ryantmoore** [comment]
I've created a single argument `api` with default value `"stream"` and built as version 2.0.1.  @kurtawirth, can you install and do a few quick runs to check that you can successfully 

- [x] omit the `api` argument, and get streamed results
- [x] specify `api = "stream"` and get streamed results
- [x] specify `api = "search"` and get search results
- [x] specify any other value for `api` and get an informative error message

**Comment by kurtawirth** [comment]
Ryan, you're a star. All worked perfectly. Closing issue and will reopen when and if other versions of the API are to be included.
