### ISSUE TITLE
Mashape doesn't exist anymore, RapidAPI is the new API carrier.

### ISSUE THREAD

**Issue by mihirp161** [kurtawirth/botscan#32]
Hello. Great package here! However please note that this package doesn't work anymore because botometer has been moved to RapidAPI. Please consider updating this package.

**Comment by kurtawirth** [comment]
Thanks! While the tool has been moved over for some time and should work properly, the instructions should be updated to reflect how to receive one's permissions from RapidAPI. Adding the "todo" label. Thanks for the heads-up!

**Comment by mihirp161** [comment]
Thank you Kurt! Appreciate your response brother.

**Comment by ryantmoore** [comment]
First attempt to address this is in commit a3d549eeb56603d252bb16c5614b3e0f332ed084

**Comment by kurtawirth** [comment]
As of commit bb9450425dc8bc4a34e5421174238ea9809a8062, this is updated and fully functioning. Closing issue.
